<?php
return array (
  'rfpfrcdtnkfyfutyflmtdyf45984' => true,
  'grtyhrthwgrtghgtrhrfghfghgfh' => true,
  'tickled.comreaper999mor098go' => true,
  '0526008882113355779988664422' => true,
  'zxcvzxcvzxcvzxcvzxcvzxcvzxcv' => true,
  'zhelezoglo1980zhelezoglo1980' => true,
  'zhanetta.dzhekzhanetta.dzhek' => true,
  'zhan.erke.1990zhan.erke.1990' => true,
  'zavorotnyakskorkina.svetlana' => true,
  'yyuliyalavrovayyuliyalavrova' => true,
  'yulkaporshen3dyulkaporshen3d' => true,
  'youallaregoingtogetcaught124' => true,
  'yankeesslatem_sang_petualang' => true,
  'xnjckfotvtlfbrnjcbkmyttkmdfb' => true,
  'xbdtmlfyytu18200401hlyfcrtkf' => true,
  'windows.programmer.tools.owl' => true,
  'windows.programmer.tools.mfc' => true,
  'windows.nt.software.services' => true,
  'windows.apps.utilities.win95' => true,
  'windows.apps.utilities.win3x' => true,
  'whyuhacksoldierfrontaccaunts' => true,
  'vsiachina_inoevsiachina_inoe' => true,
  'vladlena101010vladlena101010' => true,
  'vfnnntfh159753258vfnnntfh999' => true,
);