version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "symfony/console"
      versions: ["5.x"]
    - dependency-name: "symfony/event-dispatcher"
      versions: [ "5.x" ]
    - dependency-name: "symfony/event-dispatcher-contracts"
      versions: [ "5.x" ]
    - dependency-name: "symfony/polyfill-intl-grapheme"
      versions: [ "5.x" ]
    - dependency-name: "symfony/polyfill-intl-normalizer"
      versions: ["5.x"]
    - dependency-name: "symfony/process"
      versions: [ "5.x" ]
    - dependency-name: "symfony/routing"
      versions: [ "5.x" ]
    - dependency-name: "symfony/translation"
      versions: [ "5.x" ]
  labels:
    - "dependencies"
    - "main"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable26
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable26"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable25
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable25"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable24
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable24"

